cli support add
BGerg/weatherProject pull request #3
Opened 2020-12-22 22:23 UTC by BGerg

2020-12-23 08:42 UTC, jacksonhead requested changes
most egyenlőre csak ennyit írok, ha kijavítottad még megnézem egyszer :)

2020-12-23 08:42 UTC, jacksonhead commented on Pipfile
> +python_version = "3.9"
sztem szedd ki a python verziót vagy ha lehet csak annyit adj meg, hogy 3

2020-12-23 08:42 UTC, jacksonhead commented on src/cli/main.py
> +                    default='weatherdata',
a json kiterjesztést add meg itt

2020-12-23 08:42 UTC, jacksonhead commented on src/cli/main.py
> +parser = argparse.ArgumentParser(description = 'Get weather data from wttr.com'
Ha globálisan hagyod a parsert elég nehéz lesz a tesztelés

2020-12-23 08:42 UTC, jacksonhead commented on src/cli/main.py
> +    check_file_exist()
Ez így nem túl moduláris. Ha az applikációd tovább nő szeretnéd a már megírt kódot tudni újra felhasználni. Ezt a függvényt már kapásból nem tudnád újra felhasználni.

2020-12-23 08:42 UTC, jacksonhead commented on src/cli/main.py
>  def set_new_json_content():
`append_default_json()`

2020-12-23 08:42 UTC, jacksonhead commented on src/cli/main.py
> +    with open(json_file, 'r') as file:
Ezt a fügvvényt se tudod más json fájl olvasására használni. Nézz utánna a dependency injectionnek.

2020-12-23 08:42 UTC, jacksonhead commented on src/cli/main.py
>  def set_new_json_content():
De itt is jó lenne kicsit átgondolni, hogy a függvényed mitől függ és jó dolog-e az amitől jelenleg függ ;)

2020-12-23 08:42 UTC, jacksonhead commented on src/cli/main.py
> +    with open(json_file, 'w') as output_file:
DI ;)

2020-12-23 08:42 UTC, jacksonhead commented on src/cli/main.py
> +    weather_url_address = "http://wttr.in/"+city_name
hardcoded stringek

2020-12-23 08:42 UTC, jacksonhead commented on src/cli/main.py
> +    if not os.path.isfile(json_file):
Ha azt csinálod, hogy
`from os.path import isfile`
akkor itt azt tudod mondani, hogy
`if not isfile(json_file):`

egyébként ha így importálsz szerintem egyértelműbb, hogy mi honnan jön. Könnyebben olvasható a kód.

2020-12-23 08:42 UTC, jacksonhead commented on src/cli/main.py
> +parser.add_argument('-city',
Ezt úgy szokták, hogy:
`-c|--city`
Van egy rövid paraméter meg egy hosszú. Ilyen például a `cleartool lsreplica -l` vagy `cleartool lsreplica --long`

2020-12-23 08:42 UTC, jacksonhead commented on src/cli/main.py
> +city_name = args.city
Tesztelésnél örülni fogsz ezeknek a globáloknak :D

2020-12-23 08:42 UTC, jacksonhead commented on src/cli/main.py
> +    basic_json_file_structure = {"wttr_requests":[]}
magic stringek

2021-01-19 22:29 UTC, BGerg commented on src/cli/main.py
> +    weather_url_address = "http://wttr.in/"+city_name
most singletonba vannak téve, érdemes megnézni a appconfig.py fájlt, hogy az ottani megoldás jobb e

2021-01-20 08:39 UTC, jacksonhead requested changes

2021-01-20 08:39 UTC, jacksonhead commented on Pipfile
> +python_version = "3.9"
Töröld ezt ki. Nincs rá szükség.

2021-01-20 08:39 UTC, jacksonhead commented on src/cli/cli_parser.py
> +
Nem tudom, hogy a dupla új sor szándékos-e, gondoltam jelzem :)

2021-01-20 08:39 UTC, jacksonhead commented on src/cli/main.py
Ide is becsúszott egy új sor.

2021-01-20 08:39 UTC, jacksonhead commented on src/core/handle_weather_data.py
> +    temp = content['wttr_requests']
Nem ártana ezt is deserializálni.

2021-01-20 08:39 UTC, jacksonhead commented on src/core/appconfig.py
> +            AppConfig()
Error :) A test majd segít ezeket észrevenni :)

2021-01-20 08:39 UTC, jacksonhead commented on src/core/appconfig.py
> +        if AppConfig.__instance == None:
Pycharmot tudsz használni ingyenesen. Rengeteg dolog van amiben tud segíteni (code formatting, egyszerűbb szemantikai dolgok). Töltsd le, próbál ki ;)

2021-01-20 08:39 UTC, jacksonhead commented on src/core/appconfig.py
> +        if AppConfig.__instance is None:
Valahogy jó lenne az objektum kreálást logika nélkül megoldani.

2021-01-20 08:39 UTC, jacksonhead commented on src/core/appconfig.py
> +            self.url_address = "http://wttr.in/" + self.city_name
Magic string

2021-01-20 08:39 UTC, jacksonhead commented on src/core/appconfig.py
> +            raise Exception("You cannot create another Appconfig class")
Construktorból ne agyon dobjunk ha lehet

2021-01-20 08:39 UTC, jacksonhead commented on src/cli/main.py
> -    main()
Ideje lenne csinálni egy belépési pontot a python package-ednek. Nézz utánna a `__main__.py` jelentősségének egy pip package-nél.

2021-01-20 08:39 UTC, jacksonhead commented on src/cli/main.py
> -    main()
Nekem egyébként nem sikerült CLI-ből elindítani a programot.

2021-01-30 17:43 UTC, jacksonhead commented on weather/cli/run.py
> +    print(type(weather_datas))
debug stuff

2021-01-30 17:43 UTC, jacksonhead commented on weather/cli/run.py
> +    my_objects = JsonData(**weather_datas)
.__dict__

2021-02-01 14:53 UTC, jacksonhead commented on src/core/appconfig.py
> +        if AppConfig.__instance is None:
Gondolkodtam ezen egy picit. Ha nekünk ez a config statikus lenne akkor lenne jó a singleton. Viszont mi szeretnénk paraterizált configot kapni tehát itt úgy kellene előáĺlítani a config osztályt ahogyan azt a mostani commitban ia tetted.
Holnap majd személyesen is beszélhetünk erről, de azért is írtam ezt ide mert nen akarom elfelejteni :D

2021-02-02 21:48 UTC, merged