Develop feature custom
BGerg/weatherProject pull request #9
Opened 2021-06-12 14:04 UTC by BGerg

2021-07-19 05:57 UTC, jacksonhead requested changes
Amúgy merre van a CI-t leíró fájl?

2021-07-19 05:57 UTC, jacksonhead commented on setup.py
> +    packages=['weather', 'weather.cli', 'weather.gui', 'weather.core', 'weather.test'],
A testet is becsomagolod? Miért?

2021-07-19 05:57 UTC, jacksonhead commented on weather.egg-info/PKG-INFO
> +Metadata-Version: 1.0
Ezt nem kell hozzáadni a githez. Ezt a setuptools generálja.

2021-07-19 05:57 UTC, jacksonhead commented on weather.egg-info/SOURCES.txt
> +README.md
Ez sem kell git alá

2021-07-19 05:57 UTC, jacksonhead commented on weather.egg-info/dependency_links.txt
> +
nem kell git alá

2021-07-19 05:57 UTC, jacksonhead commented on weather.egg-info/entry_points.txt
> +[console_scripts]
nem kell git alá

2021-07-19 05:57 UTC, jacksonhead commented on weather.egg-info/top_level.txt
> +weather
nem kell git alá

2021-07-19 05:57 UTC, jacksonhead commented on weather/core/current_mode.py
> +          f"Temperature: {weather_data['temp_C']} C°\n"
Borzasztóan error prone stringként kezelni az adataidat.

2021-07-22 19:37 UTC, BGerg commented on weather/core/current_mode.py
> +          f"Temperature: {weather_data['temp_C']} C°\n"
mit jelent az hogy error prone? :D azon kivül hogy így nem lesz jó

2021-07-22 19:56 UTC, BGerg commented
> Amúgy merre van a CI-t leíró fájl?

githubon
https://github.com/BGerg/weatherProject/blob/main/.github/workflows/python-package.yml

2021-07-23 05:20 UTC, jacksonhead commented on weather/core/current_mode.py
> +          f"Temperature: {weather_data['temp_C']} C°\n"
Azt h könnyedén errorhoz vezet. Deserializálni kellene a weather_datat.

2021-08-01 18:59 UTC, merged